### ISSUE TITLE
jonatasgrosman/wav2vec2-large-xlsr-53-english/resolve/main/preprocessor_config.json 这个库都不存在了

### ISSUE THREAD

**Issue by shiyueGG** [ali-vilab/dreamtalk#1]
无法启动 访问失败 jonatasgrosman/wav2vec2-large-xlsr-53-english/resolve/main/preprocessor_config.json 这个库都不存在了

**Comment by Wentao795** [comment]
hi，我也碰到这个问题了，你能说下你是怎么解决的吗？感谢您的回复
