### ISSUE TITLE
Meaning of the 73 coefficients generated

### ISSUE THREAD

**Issue by vardanagarwal** [ali-vilab/dreamtalk#16]
Hi! In the `num_of_frames X 73` array generated by the diffusion model, do the 73 3dmm coefficients correspond with any particular keypoints of the face. I know that `64:73` are for pose, but do the initial `0:64` have some one to one mapping with the elements of face like the 68 keypoint detector has?

**Comment by YifengMa9** [comment]
0:64 are the expression coefficients for 3DMM. 3DMM, like landmarks, is also a way to describe facial motion. The 3DMM we use is based on BFM and is extracted using [Deep3DFaceRecon](https://github.com/sicxu/Deep3DFaceRecon_pytorch) (the actual script used for extraction is from the 3DMM extraction script in [PIRenderer](https://github.com/RenYurui/PIRender)).

**Comment by zhanghongyong123456** [comment]
[YifengMa9](https://github.com/YifengMa9)

Can you analyze why the results of my case are so strange, and what ways can be improved, or are not suitable for what situations
https://github.com/ali-vilab/dreamtalk/issues/14
