### ISSUE TITLE
mayf18@mails.tsinghua.edu.cn无法发送邮件

### ISSUE THREAD

**Issue by gongmm** [ali-vilab/dreamtalk#28]
收件地址：[mayf18@mails.tsinghua.edu.cn](mailto:mayf18@mails.tsinghua.edu.cn)
服务器返回码：
rcpt handle timeout,last handle info: Host [mails.tsinghua.edu.cn](http://mails.tsinghua.edu.cn/)(166.111.204.9) command HELO respond timeout or disconnected

**Comment by YifengMa9** [comment]
已经给您发送checkpoints了

**Comment by caimingshuo** [comment]
您好，我在发送邮件时候提示：
“由于系统找不到电子邮件地址 mayf18@mails.tsinghua.edu.cn，或该地址无法接收邮件，因此无法递送您的邮件。”
可以麻烦您给看一下吗

**Comment by caimingshuo** [comment]
我的邮箱是caimingshoo@gmail.com，十分感谢！
